apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: prod  # Replace with dev, staging, or prod
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081  # You can choose a port between 30000-32767 or omit this to auto-assign...........
